twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        cumlouder_images_base_url: https://w0.imgcm.com/modelos
